//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTech.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QTech.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បន្ថែម.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ស្វែងរកបន្ថែម.
        /// </summary>
        public static string AdvanceSearch {
            get {
                return ResourceManager.GetString("AdvanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទាំងអស់.
        /// </summary>
        public static string All_ {
            get {
                return ResourceManager.GetString("All_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អតិថិជនទាំងអស់.
        /// </summary>
        public static string AllCustomer {
            get {
                return ResourceManager.GetString("AllCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទឹកប្រាក់.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap billing {
            get {
                object obj = ResourceManager.GetObject("billing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap category {
            get {
                object obj = ResourceManager.GetObject("category", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Category_img {
            get {
                object obj = ResourceManager.GetObject("Category_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ប្រភេទទំនិញ.
        /// </summary>
        public static string Categorys {
            get {
                return ResourceManager.GetString("Categorys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Christmas_Big_Sale_icon {
            get {
                object obj = ResourceManager.GetObject("Christmas-Big-Sale-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បិទ.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseDateEntery_img {
            get {
                object obj = ResourceManager.GetObject("CloseDateEntery_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បិទបញ្ជី.
        /// </summary>
        public static string CloseEntryData {
            get {
                return ResourceManager.GetString("CloseEntryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ផេង ​​​​រី ផ្គត់ផ្គង់ខ្សាច់ និងថ្មគ្រប់ប្រភេទ.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CornerLeft {
            get {
                object obj = ResourceManager.GetObject("CornerLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CornerRight {
            get {
                object obj = ResourceManager.GetObject("CornerRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បង្កើតវិក័យប័ត្រ.
        /// </summary>
        public static string CreateInvoice {
            get {
                return ResourceManager.GetString("CreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to រូបិយប័ណ្ណ.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ដុល្លា.
        /// </summary>
        public static string Currency_Dollar {
            get {
                return ResourceManager.GetString("Currency_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to រៀល.
        /// </summary>
        public static string Currency_Khmer {
            get {
                return ResourceManager.GetString("Currency_Khmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អតិថិជន.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Customer_img32 {
            get {
                object obj = ResourceManager.GetObject("Customer_img32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap customer1 {
            get {
                object obj = ResourceManager.GetObject("customer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap customer2 {
            get {
                object obj = ResourceManager.GetObject("customer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ប្រភេទអតិថិជន.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delivery {
            get {
                object obj = ResourceManager.GetObject("delivery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ថ្ងៃធ្វើ.
        /// </summary>
        public static string DoDate {
            get {
                return ResourceManager.GetString("DoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នកដឹក.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Driver_img {
            get {
                object obj = ResourceManager.GetObject("Driver_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap employee {
            get {
                object obj = ResourceManager.GetObject("employee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Employee_img {
            get {
                object obj = ResourceManager.GetObject("Employee_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ការទូទាត់លើបុគ្គលិក.
        /// </summary>
        public static string EmployeeBill {
            get {
                return ResourceManager.GetString("EmployeeBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នកដឹក.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បុគ្គលិក.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap empty_file {
            get {
                object obj = ResourceManager.GetObject("empty_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ចាប់ពី.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ព័ត៌មានទូទៅ.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទូទៅ.
        /// </summary>
        public static string General_ {
            get {
                return ResourceManager.GetString("General_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_img {
            get {
                object obj = ResourceManager.GetObject("General_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GeneralEmployee {
            get {
                object obj = ResourceManager.GetObject("GeneralEmployee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទូទាត់ទូទៅ.
        /// </summary>
        public static string GeneralTotal {
            get {
                return ResourceManager.GetString("GeneralTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះ.
        /// </summary>
        public static string GoodName {
            get {
                return ResourceManager.GetString("GoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទំនិញ និងតម្លៃលក់ចេញ.
        /// </summary>
        public static string GoodsAndPrice {
            get {
                return ResourceManager.GetString("GoodsAndPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hide {
            get {
                object obj = ResourceManager.GetObject("Hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgCollapse {
            get {
                object obj = ResourceManager.GetObject("imgCollapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgExpand {
            get {
                object obj = ResourceManager.GetObject("imgExpand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgPayment {
            get {
                object obj = ResourceManager.GetObject("imgPayment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តម្លៃនាំចូល/គីប.
        /// </summary>
        public static string ImportPrice {
            get {
                return ResourceManager.GetString("ImportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ចំណូលចំណាយ.
        /// </summary>
        public static string IncomeOutcome {
            get {
                return ResourceManager.GetString("IncomeOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IncomeOutcome_img {
            get {
                object obj = ResourceManager.GetObject("IncomeOutcome_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to វិក័យប័ត្រ.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខវិក្កយបត្រ.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InvoiceNo_img {
            get {
                object obj = ResourceManager.GetObject("InvoiceNo_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បានទូទាត់.
        /// </summary>
        public static string InvoiceStatus_Paid {
            get {
                return ResourceManager.GetString("InvoiceStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មិនទាន់ទូទាត់ផ្តាច់.
        /// </summary>
        public static string InvoiceStatus_PaySome {
            get {
                return ResourceManager.GetString("InvoiceStatus_PaySome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to រងចាំទូទាត់.
        /// </summary>
        public static string InvoiceStatus_WaitPayment {
            get {
                return ResourceManager.GetString("InvoiceStatus_WaitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ថ្ងៃចេញវិក័យប័ត្រ.
        /// </summary>
        public static string InvoicingDate {
            get {
                return ResourceManager.GetString("InvoicingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បានទួទាត់.
        /// </summary>
        public static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទឹកប្រាក់នៅសល់.
        /// </summary>
        public static string LeftAmount {
            get {
                return ResourceManager.GetString("LeftAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ចូលប្រើប្រាស់.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logout1 {
            get {
                object obj = ResourceManager.GetObject("logout1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logout11 {
            get {
                object obj = ResourceManager.GetObject("logout11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meter {
            get {
                object obj = ResourceManager.GetObject("meter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Money {
            get {
                object obj = ResourceManager.GetObject("Money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អតិថិជន និងលេខ PO មិនអាចកែបានទេ!​ អ្នកអាចធ្វើការលុបការលក់នេះហើយបង្កើតថ្មី​ ។.
        /// </summary>
        public static string MsgCannotChangeCustomerAndPO {
            get {
                return ResourceManager.GetString("MsgCannotChangeCustomerAndPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមជ្រើសរើស​ ឬបញ្ចូលលេខបញ្ជាទិញជាមុន !.
        /// </summary>
        public static string MsgChoosePurchaseOrderNoFirst {
            get {
                return ResourceManager.GetString("MsgChoosePurchaseOrderNoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តើអ្នកពិតជាចង់លុបមែនទេ?.
        /// </summary>
        public static string MsgConfirmingRemoveSupplierPaid {
            get {
                return ResourceManager.GetString("MsgConfirmingRemoveSupplierPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បញ្ចាក់លេខសំងាត់មិនត្រឹមត្រូវ!.
        /// </summary>
        public static string MsgConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("MsgConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បានយកទៅប្រើប្រាស់ហើយ មិនអាចលុបបានទេ!.
        /// </summary>
        public static string MsgDataCurrentlyInUsed {
            get {
                return ResourceManager.GetString("MsgDataCurrentlyInUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to វិក័យប័ត្របានទូទាត់រូចរាល់ មិនអាចលុបបាប!.
        /// </summary>
        public static string MsgInvoiceAlreadyPaid {
            get {
                return ResourceManager.GetString("MsgInvoiceAlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to វិក័យប័ត្របានទូទាត់រួចរាល់ មិនអាចកែប្រែបាន!.
        /// </summary>
        public static string MsgInvoiceAlreadyPaidCannotEdit {
            get {
                return ResourceManager.GetString("MsgInvoiceAlreadyPaidCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះអ្នកប្រើប្រាស់ ឬលេខសំងាត់មិនត្រឹមត្រូវ!.
        /// </summary>
        public static string MsgNotCorrectNameOrPassword {
            get {
                return ResourceManager.GetString("MsgNotCorrectNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបញ្ចូលឈ្មោះគំរោង!.
        /// </summary>
        public static string MsgNotInputSite {
            get {
                return ResourceManager.GetString("MsgNotInputSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបញ្ចូលទិន្នន័យ ក្នុងតារាង {0}.
        /// </summary>
        public static string MsgPleaseInputDataInTable_ {
            get {
                return ResourceManager.GetString("MsgPleaseInputDataInTable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបញ្ជូលតម្លៃ.
        /// </summary>
        public static string MsgPleaseInputValue {
            get {
                return ResourceManager.GetString("MsgPleaseInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមធ្វើការជ្រើសរើស!.
        /// </summary>
        public static string MsgPleaseSelectValue {
            get {
                return ResourceManager.GetString("MsgPleaseSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ចំនួនបានបញ្ចូលលើចំនួយទំនិញដែលនៅសល់ក្នុង PO!.
        /// </summary>
        public static string MsgProductOverQty {
            get {
                return ResourceManager.GetString("MsgProductOverQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទំនិញដល់ចំនួនដែលបានកំណត់ទុកក្នុង PO ហើយ!.
        /// </summary>
        public static string MsgProductQtyReachLimit {
            get {
                return ResourceManager.GetString("MsgProductQtyReachLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Must {
            get {
                return ResourceManager.GetString("Must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះ.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មើលបន្ទាប់.
        /// </summary>
        public static string NextPaging {
            get {
                return ResourceManager.GetString("NextPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ចំណាំ.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មិនទាន់ទូទាត់.
        /// </summary>
        public static string NotYetPaid {
            get {
                return ResourceManager.GetString("NotYetPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to យល់ព្រម.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទឹកប្រាក់បានបង់.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ថ្ងៃបង់.
        /// </summary>
        public static string PayDate {
            get {
                return ResourceManager.GetString("PayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ស្ថានភាពទាំងអស់.
        /// </summary>
        public static string PayStatus_All {
            get {
                return ResourceManager.GetString("PayStatus_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មិនទាន់បានទូទាត់.
        /// </summary>
        public static string PayStatus_NotYetPaid {
            get {
                return ResourceManager.GetString("PayStatus_NotYetPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បានទូទាត់.
        /// </summary>
        public static string PayStatus_Paid {
            get {
                return ResourceManager.GetString("PayStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to រងចាំទូទាត់.
        /// </summary>
        public static string PayStatus_WaitPayment {
            get {
                return ResourceManager.GetString("PayStatus_WaitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សិទ្ធិ.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខទូស័ព្ទ.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តួនាទី.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តៃកុងឡាន.
        /// </summary>
        public static string Position_Driver {
            get {
                return ResourceManager.GetString("Position_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទីផ្សារ.
        /// </summary>
        public static string Position_Marketing {
            get {
                return ResourceManager.GetString("Position_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap power {
            get {
                object obj = ResourceManager.GetObject("power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap prepaid {
            get {
                object obj = ResourceManager.GetObject("prepaid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ត្រលប់ក្រោយ.
        /// </summary>
        public static string PreviousPaging {
            get {
                return ResourceManager.GetString("PreviousPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បោះពុម្ភ.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បោះពុម្ភវិក័យប័ត្រ.
        /// </summary>
        public static string PrintInvoice {
            get {
                return ResourceManager.GetString("PrintInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap product {
            get {
                object obj = ResourceManager.GetObject("product", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Product_img {
            get {
                object obj = ResourceManager.GetObject("Product_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Product32x32 {
            get {
                object obj = ResourceManager.GetObject("Product32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ប្រភេទទំនិញ.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះទំនិញ.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទំនិញ.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PurchaseOrder_img {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrder_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខបញ្ជាទិញ.
        /// </summary>
        public static string PurchaseOrderNo {
            get {
                return ResourceManager.GetString("PurchaseOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PurchaseOrderNo_img {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderNo_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បរិមាណ.
        /// </summary>
        public static string Qauntity {
            get {
                return ResourceManager.GetString("Qauntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Qauntity_3 {
            get {
                return ResourceManager.GetString("Qauntity_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លុប.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to របាយការណ៍.
        /// </summary>
        public static string Report_ {
            get {
                return ResourceManager.GetString("Report_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Report_img {
            get {
                object obj = ResourceManager.GetObject("Report_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Report_img32 {
            get {
                object obj = ResourceManager.GetObject("Report_img32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap report1 {
            get {
                object obj = ResourceManager.GetObject("report1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to របាយការណ៍ដឹកតាមតៃកុងឡាន.
        /// </summary>
        public static string ReportDriverDeliveryDetail {
            get {
                return ResourceManager.GetString("ReportDriverDeliveryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ការទូទាត់.
        /// </summary>
        public static string RuningBill {
            get {
                return ResourceManager.GetString("RuningBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RunningBill_img {
            get {
                object obj = ResourceManager.GetObject("RunningBill_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RyLogo {
            get {
                object obj = ResourceManager.GetObject("RyLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sale {
            get {
                object obj = ResourceManager.GetObject("sale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sale_img {
            get {
                object obj = ResourceManager.GetObject("Sale_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sale_img32 {
            get {
                object obj = ResourceManager.GetObject("sale_img32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to កាលបរិច្ឆេទលក់.
        /// </summary>
        public static string SaleDate {
            get {
                return ResourceManager.GetString("SaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មុខទំនិញលម្អិត.
        /// </summary>
        public static string SaleDetail {
            get {
                return ResourceManager.GetString("SaleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តម្លៃលក់.
        /// </summary>
        public static string SalePrice {
            get {
                return ResourceManager.GetString("SalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap salereport {
            get {
                object obj = ResourceManager.GetObject("salereport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ការលក់.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to រក្សាទុក.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ជ្រើសរើស.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to កំណត់តម្លៃទំនិញ.
        /// </summary>
        public static string SetPrice {
            get {
                return ResourceManager.GetString("SetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Setting_img {
            get {
                object obj = ResourceManager.GetObject("Setting_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ការកំណត់ប្រព័ន្ធ.
        /// </summary>
        public static string Setting_Text {
            get {
                return ResourceManager.GetString("Setting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap setting1 {
            get {
                object obj = ResourceManager.GetObject("setting1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បង្ហាញទាំងអស់.
        /// </summary>
        public static string ShowAllPaging {
            get {
                return ResourceManager.GetString("ShowAllPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to គំរោង.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Staff {
            get {
                object obj = ResourceManager.GetObject("Staff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សា្ថនភាព.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap supplier {
            get {
                object obj = ResourceManager.GetObject("supplier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap supplier1 {
            get {
                object obj = ResourceManager.GetObject("supplier1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នកផ្គត់ផ្គង់.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទៅកាន់ក្រុមហ៊ុន.
        /// </summary>
        public static string ToCompany {
            get {
                return ResourceManager.GetString("ToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ដល់.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string TopLevelNodeId {
            get {
                return ResourceManager.GetString("TopLevelNodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទៅកាន់គំរោង.
        /// </summary>
        public static string ToSite {
            get {
                return ResourceManager.GetString("ToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សរុប.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សរុបទឹកប្រាក់.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Type_img {
            get {
                object obj = ResourceManager.GetObject("Type_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តម្លៃឯកតា/គីប.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to កែប្រែ.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap user_img {
            get {
                object obj = ResourceManager.GetObject("user_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នកប្រើប្រាស់.
        /// </summary>
        public static string User_Text {
            get {
                return ResourceManager.GetString("User_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មើល.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មើលម្អិត.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
    }
}
