// <auto-generated />
namespace QTech.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v44 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v44));
        
        string IMigrationMetadata.Id
        {
            get { return "202108301335524_v4.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
