// <auto-generated />
namespace QTech.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v33 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v33));
        
        string IMigrationMetadata.Id
        {
            get { return "202107170607327_v3.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
