using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QTech.Base.Enums
{
    public enum AuthKey
    {
        Employee = 1,
        Customer = 2,
        Product = 3,
        Sale = 4,
        Supplier = 5,
        Report = 6,
        Setting = 7,
        Product_Product = 8,
        Product_Category = 9,
        Employee_Employee = 10,
        Employee_EmployeeBill = 11,
        Sale_Sale = 12,
        Sale_CreateInvoice = 13,
        Sale_PurchaseOrder = 14,
        Setting_User = 15,
        Product_Product_View = 16,
        Product_Product_Add = 17,
        Product_Product_Update = 18,
        Product_Product_Remove = 19,
        Product_Category_View = 20,
        Product_Category_Add = 21,
        Product_Category_Update = 22,
        Product_Category_Remove = 23,
        Employee_Employee_View = 24,
        Employee_Employee_Add = 25,
        Employee_Employee_Update = 26,
        Employee_Employee_Remove = 27,
        Employee_EmployeeBill_View = 28,
        Employee_EmployeeBill_Add = 29,
        Employee_EmployeeBill_Update = 30,
        Employee_EmployeeBill_Remove = 31,
        Sale_Sale_View = 32,
        Sale_Sale_Add = 33,
        Sale_Sale_Update = 34,
        Sale_Sale_Remove = 35,
        Sale_CreateInvoice_View = 36,
        Sale_CreateInvoice_Add = 37,
        Sale_CreateInvoice_Update = 38,
        Sale_CreateInvoice_Remove = 39,
        Sale_PurchaseOrder_View = 40,
        Sale_PurchaseOrder_Add = 41,
        Sale_PurchaseOrder_Update = 42,
        Sale_PurchaseOrder_Remove = 43,
        Setting_User_View = 44,
        Setting_User_Add = 45,
        Setting_User_Update = 46,
        Setting_User_Remove = 47,
        Customer_Customer = 48,
        Customer_Customer_View = 49,
        Customer_Customer_Add = 50,
        Customer_Customer_Update = 51,
        Customer_Customer_Remove = 52,
        General = 53,
        General_IncomeOutcome = 54,
        General_IncomeOutcome_View = 55,
        General_IncomeOutcome_Add = 56,
        General_IncomeOutcome_Update = 57,
        General_IncomeOutcome_Remove = 58,
        Report_DriverDeliveryDetail = 59,
        Report_IncomeExpense = 60,
        Report_Income = 61,
        Report_Expense = 62

    }
}
