////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace QTech.Component {
    
    
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
//    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
//        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
//        public static Settings Default {
//            get {
//                return defaultInstance;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        public global::Storm.Base.Helpers.UISetting USER_DATA {
//            get {
//                return ((global::Storm.Base.Helpers.UISetting)(this["USER_DATA"]));
//            }
//            set {
//                this["USER_DATA"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        public global::Storm.Base.Helpers.UISetting DefaultPrinter {
//            get {
//                return ((global::Storm.Base.Helpers.UISetting)(this["DefaultPrinter"]));
//            }
//            set {
//                this["DefaultPrinter"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        public global::Storm.Base.Helpers.UISetting DefaultFromToParam {
//            get {
//                return ((global::Storm.Base.Helpers.UISetting)(this["DefaultFromToParam"]));
//            }
//            set {
//                this["DefaultFromToParam"] = value;
//            }
//        }
//    }
//}
